/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BoxSearcherComponent: typeof import('./src/components/box/BoxSearcherComponent.vue')['default']
    IconAlterCulqui: typeof import('./src/components/icons/IconAlterCulqui.vue')['default']
    IconArrow: typeof import('./src/components/icons/IconArrow.vue')['default']
    IconBriefcase: typeof import('./src/components/icons/IconBriefcase.vue')['default']
    IconCulqui: typeof import('./src/components/icons/IconCulqui.vue')['default']
    IconDownload: typeof import('./src/components/icons/IconDownload.vue')['default']
    IconEdit: typeof import('./src/components/icons/IconEdit.vue')['default']
    IconEye: typeof import('./src/components/icons/IconEye.vue')['default']
    IconMenuBars: typeof import('./src/components/icons/IconMenuBars.vue')['default']
    IconPlus: typeof import('./src/components/icons/IconPlus.vue')['default']
    IconTrash: typeof import('./src/components/icons/IconTrash.vue')['default']
    IconUsers: typeof import('./src/components/icons/IconUsers.vue')['default']
    NavbarComponent: typeof import('./src/components/ui/NavbarComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarComponent: typeof import('./src/components/ui/SidebarComponent.vue')['default']
    Table: typeof import('./src/components/tables/table.vue')['default']
    TableComponent: typeof import('./src/components/tables/TableComponent.vue')['default']
  }
}
